In [2]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1,3,4,np.NaN,8,4])
s

0    1.0
1    3.0
2    4.0
3    NaN
4    8.0
5    4.0
dtype: float64

In [4]:
dates = pd.date_range('20100401',periods=6)
dates

DatetimeIndex(['2010-04-01', '2010-04-02', '2010-04-03', '2010-04-04',
               '2010-04-05', '2010-04-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
data = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
data

A         B         C         D
2010-04-01  0.239190 -1.293059  1.572040  0.248397
2010-04-02  0.192910 -1.013177  0.827929 -0.418419
2010-04-03  0.092265 -0.558448  1.160528  1.457165
2010-04-04 -1.357121 -0.089931  0.589897 -0.179615
2010-04-05 -0.155340  0.496811 -0.642814 -0.052642
2010-04-06 -0.100567 -0.606490 -0.281082 -0.632530

In [6]:
s = np.random.randn(6,4)
s

array([[ 0.72132671, -0.90767729, -0.45287917, -0.40475941],
       [-1.77860773, -1.11867246, -1.36509317,  0.24198728],
       [ 0.55197643, -0.3866452 , -0.01885038, -1.05213237],
       [-0.52530873, -1.11376286,  2.29422022, -0.95086486],
       [-1.99066065, -0.39360642,  1.8766901 , -1.35516911],
       [-0.47078943,  1.14085777,  0.43608841,  0.52497264]])

In [7]:
data.shape

(6, 4)

In [8]:
data.values

array([[ 0.23918995, -1.29305868,  1.57204043,  0.24839674],
       [ 0.19291046, -1.01317734,  0.82792893, -0.41841874],
       [ 0.09226524, -0.55844751,  1.16052781,  1.45716494],
       [-1.35712088, -0.08993081,  0.58989699, -0.17961531],
       [-0.15533982,  0.49681102, -0.64281434, -0.05264167],
       [-0.10056705, -0.60649027, -0.28108215, -0.6325305 ]])

In [9]:
d = {'A':1, 'B':pd.Timestamp('20190101 11:11:11'),'C':[0,1,2,3],'D':np.array([0,1,2,3])}
d

{'A': 1,
 'B': Timestamp('2019-01-01 11:11:11'),
 'C': [0, 1, 2, 3],
 'D': array([0, 1, 2, 3])}

In [10]:
df = pd.DataFrame(d)
df

A                   B  C  D
0  1 2019-01-01 11:11:11  0  0
1  1 2019-01-01 11:11:11  1  1
2  1 2019-01-01 11:11:11  2  2
3  1 2019-01-01 11:11:11  3  3

In [11]:
df.dtypes

A             int64
B    datetime64[ns]
C             int64
D             int64
dtype: object

In [12]:
df.A

0    1
1    1
2    1
3    1
Name: A, dtype: int64

In [13]:
df.B

0   2019-01-01 11:11:11
1   2019-01-01 11:11:11
2   2019-01-01 11:11:11
3   2019-01-01 11:11:11
Name: B, dtype: datetime64[ns]

In [14]:
type(df.A)

pandas.core.series.Series

In [15]:
data.head(2)

A         B         C         D
2010-04-01  0.23919 -1.293059  1.572040  0.248397
2010-04-02  0.19291 -1.013177  0.827929 -0.418419

In [16]:
data.tail()

A         B         C         D
2010-04-02  0.192910 -1.013177  0.827929 -0.418419
2010-04-03  0.092265 -0.558448  1.160528  1.457165
2010-04-04 -1.357121 -0.089931  0.589897 -0.179615
2010-04-05 -0.155340  0.496811 -0.642814 -0.052642
2010-04-06 -0.100567 -0.606490 -0.281082 -0.632530

In [17]:
data.index

DatetimeIndex(['2010-04-01', '2010-04-02', '2010-04-03', '2010-04-04',
               '2010-04-05', '2010-04-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
data.values

array([[ 0.23918995, -1.29305868,  1.57204043,  0.24839674],
       [ 0.19291046, -1.01317734,  0.82792893, -0.41841874],
       [ 0.09226524, -0.55844751,  1.16052781,  1.45716494],
       [-1.35712088, -0.08993081,  0.58989699, -0.17961531],
       [-0.15533982,  0.49681102, -0.64281434, -0.05264167],
       [-0.10056705, -0.60649027, -0.28108215, -0.6325305 ]])

In [19]:
data.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.181444 -0.510716  0.537750  0.070393
std    0.596897  0.643141  0.849559  0.743707
min   -1.357121 -1.293059 -0.642814 -0.632530
25%   -0.141647 -0.911506 -0.063337 -0.358718
50%   -0.004151 -0.582469  0.708913 -0.116128
75%    0.167749 -0.207060  1.077378  0.173137
max    0.239190  0.496811  1.572040  1.457165

In [20]:
data.shape

(6, 4)

In [21]:
data.sort_index(axis=1,ascending=False)

D         C         B         A
2010-04-01  0.248397  1.572040 -1.293059  0.239190
2010-04-02 -0.418419  0.827929 -1.013177  0.192910
2010-04-03  1.457165  1.160528 -0.558448  0.092265
2010-04-04 -0.179615  0.589897 -0.089931 -1.357121
2010-04-05 -0.052642 -0.642814  0.496811 -0.155340
2010-04-06 -0.632530 -0.281082 -0.606490 -0.100567

In [22]:
data.sort_index(axis=0,ascending=True)

A         B         C         D
2010-04-01  0.239190 -1.293059  1.572040  0.248397
2010-04-02  0.192910 -1.013177  0.827929 -0.418419
2010-04-03  0.092265 -0.558448  1.160528  1.457165
2010-04-04 -1.357121 -0.089931  0.589897 -0.179615
2010-04-05 -0.155340  0.496811 -0.642814 -0.052642
2010-04-06 -0.100567 -0.606490 -0.281082 -0.632530

In [23]:
data.sort_values(by='A')

A         B         C         D
2010-04-04 -1.357121 -0.089931  0.589897 -0.179615
2010-04-05 -0.155340  0.496811 -0.642814 -0.052642
2010-04-06 -0.100567 -0.606490 -0.281082 -0.632530
2010-04-03  0.092265 -0.558448  1.160528  1.457165
2010-04-02  0.192910 -1.013177  0.827929 -0.418419
2010-04-01  0.239190 -1.293059  1.572040  0.248397

In [24]:
data.T.shape

(4, 6)

In [25]:
data.A

2010-04-01    0.239190
2010-04-02    0.192910
2010-04-03    0.092265
2010-04-04   -1.357121
2010-04-05   -0.155340
2010-04-06   -0.100567
Freq: D, Name: A, dtype: float64

In [26]:
data[1:2]

A         B         C         D
2010-04-02  0.19291 -1.013177  0.827929 -0.418419

In [27]:
# data['20100402']
data['20100402':'20100403']

A         B         C         D
2010-04-02  0.192910 -1.013177  0.827929 -0.418419
2010-04-03  0.092265 -0.558448  1.160528  1.457165

In [28]:
# 认index
data.loc['20100402':'20100403']


A         B         C         D
2010-04-02  0.192910 -1.013177  0.827929 -0.418419
2010-04-03  0.092265 -0.558448  1.160528  1.457165

In [29]:
data.iloc(1)

In [30]:
# 认位置,半开区间
data.iloc[1:2]
# data.iat[1,1] 高效

A         B         C         D
2010-04-02  0.19291 -1.013177  0.827929 -0.418419

In [31]:
data.iloc[0:2,1:2]

B
2010-04-01 -1.293059
2010-04-02 -1.013177

In [32]:
data.iloc[:,1:2]

B
2010-04-01 -1.293059
2010-04-02 -1.013177
2010-04-03 -0.558448
2010-04-04 -0.089931
2010-04-05  0.496811
2010-04-06 -0.606490

In [33]:
data.loc[:,['A','B']]

A         B
2010-04-01  0.239190 -1.293059
2010-04-02  0.192910 -1.013177
2010-04-03  0.092265 -0.558448
2010-04-04 -1.357121 -0.089931
2010-04-05 -0.155340  0.496811
2010-04-06 -0.100567 -0.606490

In [34]:
data.loc['20100402':'20100403',['A','B']]

A         B
2010-04-02  0.192910 -1.013177
2010-04-03  0.092265 -0.558448

In [35]:
data.loc['20100402','B']

-1.0131773443412657

In [36]:
data.at[pd.Timestamp('20100402'),'B']

-1.0131773443412657

In [37]:
data[data>0]

A         B         C         D
2010-04-01  0.239190       NaN  1.572040  0.248397
2010-04-02  0.192910       NaN  0.827929       NaN
2010-04-03  0.092265       NaN  1.160528  1.457165
2010-04-04       NaN       NaN  0.589897       NaN
2010-04-05       NaN  0.496811       NaN       NaN
2010-04-06       NaN       NaN       NaN       NaN

In [38]:
data2 = data.copy()

In [39]:

tag = [1,2,3,4,5,6]
data2['tag'] = tag
data2

A         B         C         D  tag
2010-04-01  0.239190 -1.293059  1.572040  0.248397    1
2010-04-02  0.192910 -1.013177  0.827929 -0.418419    2
2010-04-03  0.092265 -0.558448  1.160528  1.457165    3
2010-04-04 -1.357121 -0.089931  0.589897 -0.179615    4
2010-04-05 -0.155340  0.496811 -0.642814 -0.052642    5
2010-04-06 -0.100567 -0.606490 -0.281082 -0.632530    6

In [40]:
tag_list = ['a'] * 2 + ['b'] * 2 + ['c'] * 2
data2['tag_list'] = tag_list
data2

A         B         C         D  tag tag_list
2010-04-01  0.239190 -1.293059  1.572040  0.248397    1        a
2010-04-02  0.192910 -1.013177  0.827929 -0.418419    2        a
2010-04-03  0.092265 -0.558448  1.160528  1.457165    3        b
2010-04-04 -1.357121 -0.089931  0.589897 -0.179615    4        b
2010-04-05 -0.155340  0.496811 -0.642814 -0.052642    5        c
2010-04-06 -0.100567 -0.606490 -0.281082 -0.632530    6        c

In [41]:
data2[data2.tag_list.isin(['a','b'])]


A         B         C         D  tag tag_list
2010-04-01  0.239190 -1.293059  1.572040  0.248397    1        a
2010-04-02  0.192910 -1.013177  0.827929 -0.418419    2        a
2010-04-03  0.092265 -0.558448  1.160528  1.457165    3        b
2010-04-04 -1.357121 -0.089931  0.589897 -0.179615    4        b

In [42]:
data.iat[0,0] = 100
data

A         B         C         D
2010-04-01  100.000000 -1.293059  1.572040  0.248397
2010-04-02    0.192910 -1.013177  0.827929 -0.418419
2010-04-03    0.092265 -0.558448  1.160528  1.457165
2010-04-04   -1.357121 -0.089931  0.589897 -0.179615
2010-04-05   -0.155340  0.496811 -0.642814 -0.052642
2010-04-06   -0.100567 -0.606490 -0.281082 -0.632530

In [43]:
data.A = range(6)
data

A         B         C         D
2010-04-01  0 -1.293059  1.572040  0.248397
2010-04-02  1 -1.013177  0.827929 -0.418419
2010-04-03  2 -0.558448  1.160528  1.457165
2010-04-04  3 -0.089931  0.589897 -0.179615
2010-04-05  4  0.496811 -0.642814 -0.052642
2010-04-06  5 -0.606490 -0.281082 -0.632530

In [44]:
data.B = 200
data

A    B         C         D
2010-04-01  0  200  1.572040  0.248397
2010-04-02  1  200  0.827929 -0.418419
2010-04-03  2  200  1.160528  1.457165
2010-04-04  3  200  0.589897 -0.179615
2010-04-05  4  200 -0.642814 -0.052642
2010-04-06  5  200 -0.281082 -0.632530

In [45]:
# error
# data.C = range(5)


In [50]:
data.iloc[:, 2:4] = 1000
data

A    B     C     D
2010-04-01  0  200  1000  1000
2010-04-02  1  200  1000  1000
2010-04-03  2  200  1000  1000
2010-04-04  3  200  1000  1000
2010-04-05  4  200  1000  1000
2010-04-06  5  200  1000  1000